spring:
  application:
     name: audit-service  # Service registers under this name
  activemq:
    in-memory: true
    pool:
      enabled: false
#  sleuth:
#    log:
#      json:
#        enabled: true

logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wex'
  level:
    org.springframework.web: DEBUG
    org.hibernate: DEBUG

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}