server:
  port: 8888

#management:
#  context-path: /admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
#    statusPageUrlPath: /admin/info
#    healthCheckUrlPath: /admin/health
    nonSecurePort: 80

spring:
  application:
    name: configserver  # Identify this application
---
#spring:
#  profiles: cloud
---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/istvanfarkas77/config-repo

logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wex'
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'